### PR TITLE
Add support for Android

### PR DESCRIPTION
**Pull request by Rudloff**
Hello,
This PR adds support for Android.
As Android is basically Linux under the hood, we can reuse the Linux function.

### CODE REVIEW

**Comment by LinusU** [comment]
Awesome!

**Comment by LinusU** [comment]
Released as 1.2.0

**Comment by Rudloff** [comment]
Thanks!
Would it be possible to publish 1.2.0 on NPM as well please?

**Comment by LinusU** [comment]
sorry about that 🙈 fixed!

**Comment by Rudloff** [comment]
Thanks!

**Pull request merged**
